### ISSUE TITLE
Training Bug

### ISSUE THREAD

**Issue by xiaoyaolovlife** [benhenryL/Deblurring-3D-Gaussian-Splatting#14]
Loading Training Cameras
IMAGE RESOLUTION:  (600, 400)
Loading Test Cameras
IMAGE RESOLUTION:  (600, 400)
Number of points at initialisation :  4960
Training progress:   0%|                                                                                                                                                                                 | 0/20000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 282, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from, args.deblur)
  File "train.py", line 103, in training
    lambda_s=opt.lambda_s, lambda_p=opt.lambda_p, max_clamp=opt.max_clamp)
  File "/home/xiaoyao/project/deblurring/Deblurring-3D-Gaussian-Splatting/gaussian_renderer/__init__.py", line 52, in render
    debug=pipe.debug
TypeError: __new__() missing 2 required positional arguments: 'depth_threshold' and 'iteration'
Training progress:   0%|       

Does Anyone face the same difficulty? Thanks!

**Comment by benhenryL** [comment]
Hello, sorry for the late response, I was busy with the deadline rush. 
GaussianRasterizer class does not take those parameters at initialization. I just cloned the repo and found it worked well. Hope you already handled this problem but if it's not, would you like to check if there are any newly added parameters in GaussianRasterizer?
Thanks!

**Comment by xiaoyaolovlife** [comment]
Thank you very much！I have solved this problem because I used wrong submodule version. Your code is correct.
![Uploading image.png…]()
