### ISSUE TITLE
Great work! May I ask when you will be able to open source the code?

### ISSUE THREAD

**Issue by Lixuanhe** [benhenryL/Deblurring-3D-Gaussian-Splatting#6]
Great work! May I ask when you will be able to open source the code? Currently related work such as 'BAD-Gaussians' has open source code.

**Comment by DiHubKi** [comment]
never

**Comment by Lixuanhe** [comment]
> never

Thank you for your reply. I think you are most likely right! Haha.

**Comment by benhenryL** [comment]
Hello, thanks for your attention to our work, and feel very sorry for the late response.

We are currently working on one additional experiment, and a paper with new features and codes will be uploaded soon, right after it is done.

Thanks for your patience.

**Comment by benhenryL** [comment]
Hi, our paper and codes are updated. We sincerely appreciate your patience. Thanks!
