### ISSUE TITLE
About your rerunning of COLMAP

### ISSUE THREAD

**Issue by haeyun-choi** [benhenryL/Deblurring-3D-Gaussian-Splatting#8]
First of all, thank you for your great work.

It is mentioned that you reran COLMAP on the Deblur-NeRF dataset, but the poses I obtained directly by running COLMAP do not work, so I am leaving an issue.
( I did the test with the synthetic camera motion blur dataset named 'blurwine' )

What process did you use to reacquire the camera poses? 

Thank you in advance.

**Comment by benhenryL** [comment]
Hi, thanks for your attention to our work!

Following is a set of changes in the default hyperparameters of COLAMP.

Feature extractor
- camera_model: SIMPLE_PINHONE
- single_camera: True
- estimate_affine_shape: True
- domain_size_pooling: True

Exhaustive matcher
- guided_matching: True

Mapper
- min_num_matches: 16
- mapper_refine_extra: False
- tri_min_angle: 1.5

I fixed all the hyperparameters other than ‘tri_min_angle’ of COLAMP mapper, which is different across the scenes.

Hope this helps, and please let me know if you have any other problems.

Thanks

**Comment by haeyun-choi** [comment]
Thank you for the quick response and for sharing the changed settings of COLMAP.

Q1.
When extracting camera poses for the LLFF dataset using the default COLMAP settings, 
I noticed that the camera model is selected as the simple_radial model. 

I also observed that you appropriately modified the code in line 98 of ./scene/dataset_readers.py in your repository to reflect this.

Despite this, there is a specific reason why you changed the camera settings in COLMAP?

Q2.
Additionally, I am curious whether the mapper_refine_extra: False setting you mentioned is the same as setting refine_extra_camera_params to False in the Bundle section of COLMAP's Reconstruction options.

Thank you in advance and congratulations on having your paper accepted at the ECCV 2024.

**Comment by benhenryL** [comment]
Q1. I tried both simple_radial and simple_pinhole, but I couldn’t find the differences empirically. I mean they must work in different ways (ex. estimating focal length), but there was no difference in experimental results so I just picked simple_pinhole.
But I used default (provided by deblur dataset) camera poses and point cloud for some scenes, and they used simple_radial so I added a few codes at ./scene/dataset_readers.py in a way that it can work on both types of camera models.

Q2. Right. It is 'refine_extra_camera_params' in Bundle section of COLAMP's reconstruction. Sorry for the confusion.

Please let me know if you have another question, and thank you for your words!

**Comment by haeyun-choi** [comment]
Thank you for your response. I will close the issue now. 
Once again, I appreciate your excellent research.
